---
title: Blog
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Prashant Sharma
bio: A Man who travels the world eating noodles
description: A blog about technology and stuff related
external-image: false
picture: assets/images/PrashantSharma.jpg
resume: true
resume-external: true
resume-url: https://google.com/?q=my+resume
url: http://sharmapacific.in
permalink: "/:title/"
disqus:
  shortname: 
  categories:
  - 
  - 
linkedin: prashant-sharma-4572b3b4
twitter: sharmapacific1
github: sharmapacific
medium: 
email: sharma.pacific1@gmail.com
authors:
  johndoe:
    name: John Doe
    bio: A Man who travels the world eating noodles
    external-image: false
    picture: assets/images/profile.jpg
    twitter: johndoe
  jamesfoster:
    name: James Foster
    bio: A Man who develops software with coffee
    external-image: false
    picture: assets/images/james.jpg
    twitter: jamesfoster
  linkedin: prashant-sharma-4572b3b4
width: normal
projects: false
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links:
- blog
show-author: true
animation: true
plugins:
- jekyll-seo-tag
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-admin
- jekyll-sitemap
jekyll-mentions:
  base_url: https://github.com
compress_html:
  ignore:
    envs:
    - development
    - stage
exclude:
- travis.sh
- Rakefile
- README.md
- Gemfile
- Gemfile.lock
- FAQ.md
